### ISSUE TITLE
1.21?

### ISSUE THREAD

**Issue by meowinqq** [JustAHuman-xD/PackPresets#1]
i hate to be that person and i don't mean to bother! just inquiring about whether or not this mod will be receiving an update for 1.21 compatibility :") thank you for your time!

**Comment by JustAHuman-xD** [comment]
It should hopefully yeah! just been running into a couple issues, I do plan on updating it!

**Comment by JustAHuman-xD** [comment]
Once I get the 1.20.6 update finished (whats giving me grief atm), the 1.21 update should be quick from there

**Comment by ODF4** [comment]
I would also love to see this mod eventually updated to support 1.21.1, but of course take as much time as you need with it! I'm writing this comment just to say that I've been wanting something like this for so long, so thank you so much for developing this amazing mod!

**Comment by JustAHuman-xD** [comment]
It's been updated! Out on [modrinth](https://modrinth.com/mod/pack-presets) and processing on [curseforge](https://www.curseforge.com/minecraft/mc-mods/pack-presets)
